### ISSUE TITLE
Create class specification for splitting into train and test sets (X and Y)

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/pymleda#10]

**Comment by Saule-Atymtayeva** [comment]
Write function code and tests in close temporal proximity with each other. The process of writing function code and test cases will be iterative; there will be several rounds of writing tests → function improvement → writing more tests → function improvement → writing more tests → function improvement, etc.

**Comment by tanmaysharma19** [comment]
Addressed in #33.
