### ISSUE TITLE
Create function specification for identifying and imputing NAs

### ISSUE THREAD

**Issue by yaz-saleh** [UBC-MDS/pymleda#9]

**Comment by Saule-Atymtayeva** [comment]
Done!

**Comment by Saule-Atymtayeva** [comment]
Write function code and tests in close temporal proximity with each other. The process of writing function code and test cases will be iterative; there will be several rounds of writing tests → function improvement → writing more tests → function improvement → writing more tests → function improvement, etc.

**Comment by Saule-Atymtayeva** [comment]
https://github.com/UBC-MDS/pymleda/blob/feature-impute_na_function/pymleda/pymleda.py

**Comment by tanmaysharma19** [comment]
Addressed in #29.
